### PR TITLE
CSS: Fix unclickable padding

### PR DESCRIPTION
**Pull request by fangyi-zhou**
It turns out padding on li is not clickable, we need to move that to a
element

I'm not an expert in CSS / front end, I kind of hacked some CSS and it
somehow worked :)

### CODE REVIEW

**Comment by fangyi-zhou** [comment]
#21

**Comment by fangyi-zhou** [comment]
hopefully i didn't break other css...

**Comment by fallax** [comment]
This appears to cause the icon next to each item to disappear.

broken

This is what it should be like:

correct

The general principle of what you are doing is correct though, I will modify it so that the icons appear correctly.

**Comment by fallax** [comment]
Fixed by https://github.com/genderkit/genderkit/commit/5f156edc26c72255d5e82070a0312388713406f6 instead. Thanks for the PR, the general principle behind it was correct and allowed me to fix this simply.

**Pull request closed without merging**
